//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeriTabani : DbContext
    {
        public VeriTabani()
            : base("name=VeriTabani")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_Hastaliklar> tbl_Hastaliklar { get; set; }
        public virtual DbSet<tbl_Ilac> tbl_Ilac { get; set; }
        public virtual DbSet<tbl_Kisiler> tbl_Kisiler { get; set; }
        public virtual DbSet<tbl_Randevular> tbl_Randevular { get; set; }
        public virtual DbSet<tbl_Recete> tbl_Recete { get; set; }
    }
}
