//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Randevular
    {
        public int randevu_id { get; set; }
        public string randevu_hastahane { get; set; }
        public string randevu_doktor { get; set; }
        public string randevu_klinik { get; set; }
        public System.DateTime randevu_tarih { get; set; }
        public int kisi_id { get; set; }
    
        public virtual tbl_Kisiler tbl_Kisiler { get; set; }
    }
}
