//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Recete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Recete()
        {
            this.tbl_Ilac = new HashSet<tbl_Ilac>();
        }
    
        public int recete_id { get; set; }
        public int kisi_id { get; set; }
        public int recete_no { get; set; }
        public System.DateTime recete_tarih { get; set; }
        public string recete_tur { get; set; }
        public string recete_hekim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ilac> tbl_Ilac { get; set; }
        public virtual tbl_Kisiler tbl_Kisiler { get; set; }
    }
}
