//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hastaliklar
    {
        public int hastalik_id { get; set; }
        public int kisi_id { get; set; }
        public string hastalik_tani { get; set; }
        public System.DateTime hastalik_tarih { get; set; }
        public string hastalik_klinik { get; set; }
        public string hastalik_hekim { get; set; }
    
        public virtual tbl_Kisiler tbl_Kisiler { get; set; }
    }
}
