//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ilac
    {
        public int ilac_id { get; set; }
        public int recete_id { get; set; }
        public string ilan_name { get; set; }
        public byte ilac_doz { get; set; }
    
        public virtual tbl_Recete tbl_Recete { get; set; }
    }
}
